version: '3.7'

services:
  # Service
  backend-multirole-app:
    # Build the image from the Dockerfile in the current directory
    build: .
    # Name of the container
    container_name: backend-multirole
    # Restart the container always
    restart: always
    # Environment variables
    env_file:
      - .env
    # Expose the port
    ports:
      - "${APP_PORT}:${APP_PORT}"
